version: "3.9"

services:
  api:
    environment:
      - API_PORT=8008
    volumes:
      - ./data:/app/data

  frontend:
    ports:
      - "${FRONTEND_PORT:-8080}:80"
    environment:
      - API_PORT=8008

